#!/bin/sh

# This trivially compiles all known-good configurations

build_one () {
    make -s clean
    echo "####################"
    echo "Build for " "$1"
    make -s -k $2
    test -f ppsi.o && size ppsi.o
    test -f ppsi && size ppsi
}

build_diags () {
    build_one "arch \"$ARCH\", ext \"$PROTO_EXT\", no diag"
    build_one "arch \"$ARCH\", ext \"$PROTO_EXT\", mini diag" HAS_DIAG=y
    build_one "arch \"$ARCH\", ext \"$PROTO_EXT\", full diag" HAS_FULL_DIAG=y
}

build_ext () {
    unset PROTO_EXT
    build_diags
    #export PROTO_EXT=one
    #build_diags
}

for var in HAS_DIAG HAS_FULL_DIAG CROSS_COMPILE ARCH; do
    unset $var
done

# Build for default ARCH first
unset ARCH
build_ext

# Finally, loop over all archs, using our local names for compilers
PREFIX_bare_linux=""
PREFIX_spec="/opt/gcc-lm32/bin/lm32-elf-"

for a in bare-linux spec; do
    export ARCH=$a
    ARCH_=""
    eval export CROSS_COMPILE="\${PREFIX_$(echo $ARCH | sed 's/-/_/g')}"
    build_ext
done
