# Makefile for an extended protocol.
# Alessandro Rubini for CERN, 2011 -- public domain
#
# We add to obj-y, and further undefined symbols are taken from libstd
# (i.e., code and data from the standard protocol)

P := proto-ext-$(PROTO_EXT)

OBJ-y += $P/ext-wr.o
