
# All files are under directory D: I'm lazy
D := proto-ext-whiterabbit

OBJ-y += $D/fsm-table.o \
	$D/hooks.o \
	$D/common-fun.o \
	$D/state-wr-present.o \
	$D/state-wr-m-lock.o \
	$D/state-wr-s-lock.o \
	$D/state-wr-locked.o \
	$D/state-wr-calibration.o \
	$D/state-wr-calibrated.o \
	$D/state-wr-resp-calib-req.o \
	$D/state-wr-link-on.o \
	$D/wr-msg.o \
	$D/wr-servo.o
