# Alessandro Rubini for CERN, 2013 -- public domain

# This Makefile in included by architectures that select time-bare
# Object files are added to libarch, so they are picked on demand.

OBJ-libarch += \
	time-bare/bare-time.o \
	time-bare/bare-socket.o 
