# Alessandro Rubini for CERN, 2013 -- public domain

# This Makefile in included by arch-wrpc.
# Object files are added to libarch, so they are picked on demand.

OBJ-libarch += \
	time-wrpc/wrpc-time.o \
	time-wrpc/wrpc-socket.o 
