# Hosted environment: build the final exectuable

# All files are under D: I'm lazy
D := proto-standard

OBJ-y += $D/fsm-table.o \
	$D/state-initializing.o \
	$D/state-faulty.o \
	$D/state-disabled.o \
	$D/state-listening.o \
	$D/state-pre-master.o \
	$D/state-master.o \
	$D/state-passive.o \
	$D/state-uncalibrated.o \
	$D/state-slave.o \
	$D/common-fun.o \
	$D/bmc.o \
	$D/msg.o \
	$D/arith.o \
	$D/servo.o \
	$D/hooks.o \
	$D/timeout.o \
	$D/open-close.o
