# This Makefile in included by architectures that select time-sim
# as a default, or by builds with explicit TIME=sim.
# Object files are added straight, as they are always needed

OBJ-y += time-sim/sim-time.o time-sim/sim-socket.o
