# This Makefile in included by architectures that select time-unix
# as a default, or by builds with explicit TIME=unix.
# Object files are added straight, as they are always needed

OBJ-y += \
	time-unix/unix-time.o \
	time-unix/unix-socket.o 
