# Alessandro Rubini for CERN, 2013 -- public domain

# This Makefile in included by architectures that select time-unix
# as a default, or by builds with explicit TIME=unix.
# Object files are added to libarch, so they are picked on demand.

OBJ-libarch += \
	time-unix/unix-time.o \
	time-unix/unix-socket.o 
